variable "aws_region" {
  description = "AWS region to deploy in"
  type        = string
  default     = "ap-south-1"
}

variable "instance_type" {
  description = "EC2 instance type (free-tier eligible)"
  type        = string
  default     = "t3.micro"
}

variable "key_name" {
  description = "Name for the AWS key pair"
  type        = string
  default     = "medicine-key"
}

variable "public_key_path" {
  description = "Path to the public key file generated by ssh-keygen"
  type        = string
  default     = "./medicine-key.pub"
}
